# Generated by Codex for the Card Vault Review MVP.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardvaultcard",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("needs_review", "Needs review"),
                    ("approved", "Approved"),
                    ("ignored", "Ignored"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="needs_review",
                max_length=32,
            ),
        ),
    ]
