# Generated by Codex for Card Vault AI extraction.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_vault", "0002_cardvaultcard_ignored_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardvaultintakesession",
            name="ai_raw_response",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
