# Generated by Django 5.1.15 on 2026-06-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_vault', '0003_cardvaultintakesession_ai_raw_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardVaultValuationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('query_used', models.TextField(blank=True)),
                ('normalized_card_key', models.CharField(blank=True, db_index=True, max_length=512)),
                ('estimated_value_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa9_value_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa9_value_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa9_value_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa10_value_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa10_value_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_psa10_value_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_confidence', models.FloatField(default=0)),
                ('confidence_label', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=16)),
                ('comp_count_total', models.PositiveIntegerField(default=0)),
                ('sold_comp_count', models.PositiveIntegerField(default=0)),
                ('active_listing_count', models.PositiveIntegerField(default=0)),
                ('guide_source_count', models.PositiveIntegerField(default=0)),
                ('scarcity_source_count', models.PositiveIntegerField(default=0)),
                ('grading_upside_score', models.FloatField(default=0)),
                ('grading_recommendation', models.TextField(blank=True)),
                ('pricing_summary', models.TextField(blank=True)),
                ('pricing_explanation', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_runs', to='card_vault.cardvaultcard')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardVaultPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_label', models.CharField(db_index=True, default='low', max_length=16)),
                ('comp_count', models.PositiveIntegerField(default=0)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='card_vault.cardvaultcard')),
                ('valuation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='card_vault.cardvaultvaluationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardVaultComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('sold_comp', 'Sold comp'), ('active_listing', 'Active listing'), ('price_guide', 'Price guide'), ('pop_report', 'Population report'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('title', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('listing_status', models.CharField(blank=True, max_length=64)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('raw_or_graded', models.CharField(db_index=True, default='raw', max_length=32)),
                ('card_match_score', models.FloatField(default=0)),
                ('player_match', models.BooleanField(default=False)),
                ('year_match', models.BooleanField(default=False)),
                ('brand_match', models.BooleanField(default=False)),
                ('product_match', models.BooleanField(default=False)),
                ('card_number_match', models.BooleanField(default=False)),
                ('parallel_match', models.BooleanField(default=False)),
                ('rookie_match', models.BooleanField(default=False)),
                ('auto_match', models.BooleanField(default=False)),
                ('relic_match', models.BooleanField(default=False)),
                ('numbered_match', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('exclusion_reason', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valuation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='card_vault.cardvaultvaluationrun')),
            ],
            options={
                'ordering': ['excluded', '-card_match_score', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='cardvaultvaluationrun',
            index=models.Index(fields=['card', '-started_at'], name='cv_valrun_card_started_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvaultvaluationrun',
            index=models.Index(fields=['status', 'confidence_label'], name='cv_valrun_status_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvaultpricesnapshot',
            index=models.Index(fields=['card', '-created_at'], name='cv_snapshot_card_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvaultpricesnapshot',
            index=models.Index(fields=['confidence_label', '-created_at'], name='cv_snapshot_conf_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvaultcomp',
            index=models.Index(fields=['valuation_run', 'source_type'], name='cv_comp_run_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvaultcomp',
            index=models.Index(fields=['excluded', 'card_match_score'], name='cv_comp_excluded_score_idx'),
        ),
    ]
