# Generated by Django 5.1.15 on 2026-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_vault', '0004_cardvaultvaluationrun_cardvaultpricesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardvaultcomp',
            name='source_type',
            field=models.CharField(choices=[('sold_comp', 'Sold comp'), ('active_listing', 'Active listing'), ('price_guide', 'Price guide'), ('pop_report', 'Population report'), ('search_hint', 'Search hint'), ('manual', 'Manual')], db_index=True, max_length=32),
        ),
    ]
