# Generated by Django 5.1.15 on 2026-06-20 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_vault', '0005_alter_cardvaultcomp_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GergVaultTrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('api_request', 'API request'), ('auth', 'Auth'), ('admin', 'Admin'), ('other', 'Other')], db_index=True, default='page_view', max_length=32)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=200)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('forwarded_for', models.CharField(blank=True, max_length=512)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('query_string_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gergvault_traffic_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='gv_traffic_type_created_idx'), models.Index(fields=['user', '-created_at'], name='gv_traffic_user_created_idx'), models.Index(fields=['status_code', '-created_at'], name='gv_traffic_status_created_idx'), models.Index(fields=['path', '-created_at'], name='gv_traffic_path_created_idx')],
            },
        ),
    ]
