# Generated by Django 5.1.15 on 2026-06-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tenants(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Tenant = apps.get_model("card_vault", "GergVaultTenant")
    Membership = apps.get_model("card_vault", "GergVaultTenantMembership")
    Session = apps.get_model("card_vault", "CardVaultIntakeSession")
    Card = apps.get_model("card_vault", "CardVaultCard")
    Location = apps.get_model("card_vault", "CardVaultLocation")

    def slug_for(user):
        raw = getattr(user, "username", "") or f"user-{user.pk}"
        slug = "-".join("".join(ch.lower() if ch.isalnum() else " " for ch in raw).split())[:240] or f"user-{user.pk}"
        base = slug
        suffix = 2
        while Tenant.objects.filter(slug=slug).exists():
            slug = f"{base}-{suffix}"
            suffix += 1
        return slug

    tenants_by_user = {}
    for user in User.objects.all():
        tenant = Tenant.objects.create(
            name=f"{getattr(user, 'username', 'User')}'s Vault",
            slug=slug_for(user),
            created_by_id=user.pk,
        )
        Membership.objects.create(tenant=tenant, user_id=user.pk, role="owner")
        tenants_by_user[user.pk] = tenant

    shared_tenant = None
    if Session.objects.filter(tenant__isnull=True, created_by__isnull=True).exists() or Card.objects.filter(tenant__isnull=True, session__isnull=True).exists():
        shared_tenant = Tenant.objects.create(name="Imported Vault", slug="imported-vault")

    for session in Session.objects.filter(tenant__isnull=True):
        tenant = tenants_by_user.get(session.created_by_id) or shared_tenant
        if tenant:
            session.tenant_id = tenant.pk
            session.save(update_fields=["tenant"])

    for card in Card.objects.filter(tenant__isnull=True).select_related("session"):
        tenant_id = card.session.tenant_id if card.session_id else None
        if tenant_id is None and shared_tenant:
            tenant_id = shared_tenant.pk
        if tenant_id:
            card.tenant_id = tenant_id
            card.save(update_fields=["tenant"])

    first_tenant = Tenant.objects.order_by("id").first()
    if first_tenant:
        Location.objects.filter(tenant__isnull=True).update(tenant=first_tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('card_vault', '0006_gergvaulttrafficevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GergVaultTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gergvault_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cardvaultcard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_vault.gergvaulttenant'),
        ),
        migrations.AddField(
            model_name='cardvaultintakesession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to='card_vault.gergvaulttenant'),
        ),
        migrations.AddField(
            model_name='cardvaultlocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='card_vault.gergvaulttenant'),
        ),
        migrations.CreateModel(
            name='GergVaultTenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='card_vault.gergvaulttenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gergvault_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'tenant'], name='gv_membership_user_tenant_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='gv_unique_tenant_user')],
            },
        ),
        migrations.RunPython(backfill_tenants, migrations.RunPython.noop),
    ]
