# Generated by Django 5.1.15 on 2026-06-20 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Profile = apps.get_model("card_vault", "GergVaultUserProfile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user_id=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('card_vault', '0007_gergvaulttenant_cardvaultcard_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GergVaultUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gergvault_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
